cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm run build && npm test"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm ls supertest express mongoose jest --depth=0"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm install"
cmd /C "where npm && npm -v && node -v"
cmd /C "echo hi"
powershell -Command "Write-Output 'hello'"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm test --verbose"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm test --verbose > test-output.txt 2>&1 && type test-output.txt"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm run build > build-log.txt 2>&1 && type build-log.txt"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm install --legacy-peer-deps"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm run ci > ci-output.txt 2>&1 && type ci-output.txt"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm install --legacy-peer-deps"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm run ci"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && npm view supertest versions --json | findstr /R /C:"6\.3\.[0-9]""
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm run ci"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI\backend && rmdir /s /q dist 2>nul ; npm run build"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm run build:backend"
cmd /C "cd /d c:\Users\N_Ngu\Sailing_AI\Sailing_AI && npm run ci"
